WIP: Translation of rendering-elements
reactjs/pt-PT.reactjs.org pull request #14
Opened 2019-02-14 23:06 UTC by fjoshuajr

2019-02-18 10:24 UTC, jbarradas commented
@fjoshuajr Is it possible for you to join Slack? You're missing some discussions, in this case, regarding the word 'rendering'. If is not possible to you to join slack, or you just don't want it, please let us know :)

2019-02-18 14:38 UTC, fjoshuajr commented
😳 thanks for reminding me, yes I will join ASAP

2019-02-19 09:46 UTC, telmogoncalves commented on content/docs/rendering-elements.md
> +Elementos são os menores blocos para a construção de aplicações React.
O que acham de `aplicações em React` ou `aplicações de React`

2019-02-22 11:34 UTC, jbarradas commented on content/docs/rendering-elements.md
> +Elementos são os menores blocos para a construção de aplicações React.
Acho que pode depender dos casos. Neste caso diria "aplicações em React".
Apesar que estamos a omitir os "em, de, o" em muitos sítios. É a tal história de "biblioteca JavaScript" ou "bilbioteca de JavaScript".

Mas não nos podemos esquecer que estamos a traduzir para português. Que usa bastante estas proposições. Não devemos simplesmente ignorá-las só porque entendemos bem o inglês.

2019-02-22 13:09 UTC, jbarradas requested changes

2019-02-22 13:09 UTC, jbarradas commented on content/docs/rendering-elements.md
> +O React DOM compara o novo elemento e seus filhos com os anteriores e somente aplica as modificações necessárias no DOM para levá-lo ao estado desejado.
```suggestion
O React DOM compara o novo elemento e seus filhos com o anterior e apenas aplica as modificações necessárias no DOM para que fique no estado desejado.
```

2019-02-22 13:09 UTC, jbarradas commented on content/docs/rendering-elements.md
> +Podes observar isto inspecionando o [último exemplo](codepen://rendering-elements/update-rendered-element) com as ferramentas do navegador:
```suggestion
Podes verificar isto inspeccionando o [último exemplo](codepen://rendering-elements/update-rendered-element) com as ferramentas do navegador:
```

2019-02-22 13:09 UTC, jbarradas commented on content/docs/rendering-elements.md
> +Podes observar isto inspecionando o [último exemplo](codepen://rendering-elements/update-rendered-element) com as ferramentas do navegador:
Aqui também podemos usar "confirmar" em vez de "verificar"

2019-02-22 13:09 UTC, jbarradas commented on content/docs/rendering-elements.md
> +![Inspector do DOM mostrando actualizações granulares](../images/docs/granular-dom-updates.gif)
```suggestion
![Actualizações granulares no inspector do DOM](../images/docs/granular-dom-updates.gif)
```

2019-02-22 13:09 UTC, jbarradas commented on content/docs/rendering-elements.md
> +Com base na nossa experiência, pensar em como a interface gráfica (_UI_) deve estar em um determinado momento, ao invés de pensar como modificá-la com o tempo, evita uma série de bugs.
```suggestion
Com base na nossa experiência, pensar em como a interface gráfica (_UI_) deve estar num determinado momento, ao invés de pensar em como modificá-la com o tempo, evita uma série de _bugs_.
```

2019-02-22 16:59 UTC, fjoshuajr commented on content/docs/rendering-elements.md
> +Elementos são os menores blocos para a construção de aplicações React.
```suggestion
Elementos são os menores blocos para a construção de aplicações em React.
```

ah pois, vou corrigir.

2019-02-22 17:03 UTC, fjoshuajr commented on content/docs/rendering-elements.md
> +>És capaz de confundir elementos com o conceito mais amplo de "componentes". Iremos introduzir componentes na [próxima seccção](/docs/components-and-props.html). Componentes são "compostos" por eleme
Boa! Vou apenas trocar compôem -> compõem na tua correcção.

2019-02-22 17:08 UTC, fjoshuajr commented on content/docs/rendering-elements.md
> +Suponhamos que exista um `<div>` em algum lugar no teu ficheiro HTML:
```suggestion
Suponhamos que existe um `<div>` algures no teu ficheiro HTML:
```

@jbarradas, por mais que 'soe' melhor, elementos _do_ DOM [estão](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/div) todos no masculino.

2019-02-22 17:38 UTC, fjoshuajr commented
@jbarradas feedback addressed

2019-02-23 17:58 UTC, jbarradas commented on content/docs/rendering-elements.md
> +Suponhamos que exista um `<div>` em algum lugar no teu ficheiro HTML:
Aqui estamos a falar de uma tag html. Uma <div>. Eu pelo menos nunca disse, "um div", tu dizes? :p 
cc: @telmogoncalves

2019-02-23 18:14 UTC, jbarradas commented on content/docs/rendering-elements.md
> +Com o que aprendemos até agora, a única forma de actualizar a interface gráfica (_UI_) é criando um novo elemento e passá-lo ao `ReactDOM.render()`.
Este não ficou resolvido. Penso que para usar o "passá-lo", teríamos que dizer "..é criar um novo elemento e passá-lo".
A partir do momento que utilizámos "criando", teremos que manter o tempo verbal.

2019-02-23 19:28 UTC, fjoshuajr commented on content/docs/rendering-elements.md
> +Suponhamos que exista um `<div>` em algum lugar no teu ficheiro HTML:
Eu digo 'uma <div>'. Mas também digo 'um <p> ou um <h1>' que também são tags.
É mais para uniformizar.

2019-02-23 22:31 UTC, jbarradas commented on content/docs/rendering-elements.md
> +Suponhamos que exista um `<div>` em algum lugar no teu ficheiro HTML:
Sim, percebo! E concordo ;)

2019-03-04 08:57 UTC, 0xtelmo approved these changes

2019-05-05 00:38 UTC, merged