Translation of reference-javascript-environment-requirements
reactjs/pt-PT.reactjs.org pull request #16
Opened 2019-02-16 11:25 UTC by fjoshuajr

2019-02-23 18:23 UTC, jbarradas requested changes

2019-02-23 18:23 UTC, jbarradas commented on content/docs/reference-javascript-environment-requirements.md
> +O React 16 depende dos tipos de colecção [Map](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Map) e [Set](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Re
```suggestion
O React 16 depende dos tipos de colecção [Map](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Map) e [Set](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Set). Para suportar navegadores antigos e dispositivos que ainda não tenham estes tipos de forma nativa (ex: IE < 11) ou tenham uma implementação incompatível (ex. IE 11), considera a inclusão de um _polyfill_ global no _bundle_ da tua aplicação, tal como o pacote [core-js](https://github.com/zloirock/core-js) ou [babel-polyfill](https://babeljs.io/docs/usage/polyfill/).
```

2019-02-23 18:23 UTC, jbarradas commented on content/docs/reference-javascript-environment-requirements.md
> +Um ambiente com _polyfill_ para o React 16, que usa core-js para dar suporte à navegadores antigos é mais ou menos assim:
```suggestion
Um ambiente com _polyfill_ para o React 16, que usa core-js para dar suporte a navegadores antigos é mais ou menos assim:
```

2019-02-23 19:25 UTC, fjoshuajr commented
@jbarradas feedback addressed 🙂

2019-02-23 22:28 UTC, jbarradas approved these changes

2019-03-04 08:57 UTC, 0xtelmo approved these changes

2019-03-04 18:53 UTC, fjoshuajr commented
🚀

2019-03-04 18:54 UTC, merged