Translation of reference-react-dom-server.md
reactjs/pt-PT.reactjs.org pull request #7
Opened 2019-02-12 20:31 UTC by fjoshuajr

#1

2019-02-13 09:30 UTC, 0xtelmo requested changes

2019-02-13 09:30 UTC, telmogoncalves commented on content/docs/reference-react-dom-server.md
> +Se invocares [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de eventos (_eve
`[...] em um nó` ? Acho que não devemos traduzir a palavra `node`.

2019-02-13 09:30 UTC, telmogoncalves commented on content/docs/reference-react-dom-server.md
> +Se tens planos de usar o React no cliente para tornar o _markup_ interactivo, não use este método. Em vez disso, use [`renderToString`](#rendertostring) no servidor e [`ReactDOM.hydrate()`](/docs/rea
```suggestion
Se tens planos em usar o React no cliente para tornar o _markup_ interactivo, não uses este método. Em vez disso, usa [`renderToString`](#rendertostring) no servidor e [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) no cliente.
```

2019-02-13 09:30 UTC, telmogoncalves commented on content/docs/reference-react-dom-server.md
> +Renderiza um elemento React para seu HTML inicial. Retorna um [_Readable Stream_](https://nodejs.org/api/stream.html#stream_readable_streams) que gera uma string HTML. A saída HTML deste _stream_ é e
```suggestion
Renderiza um elemento React para o teu HTML inicial. Retorna um [_Readable Stream_](https://nodejs.org/api/stream.html#stream_readable_streams) que gera uma string HTML. A saída HTML deste _stream_ é exactamente igual à que [`ReactDOMServer.renderToString`](#rendertostring) retornaria. Podes usar este método para gerar HTML no servidor e enviar o _markup_ no _request_ inicial para ter carregamentos de página mais rápidos e para permitir que motores de busca rastreiem as tuas páginas para fins de _SEO_.
```

2019-02-13 09:30 UTC, telmogoncalves commented on content/docs/reference-react-dom-server.md
> +Se invocares [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de eventos (_eve
Isto já foi traduzido. É erro da traduzão em EN? Isto está repetido.

2019-02-13 09:30 UTC, telmogoncalves commented on content/docs/reference-react-dom-server.md
> +> O _stream_ retornado por este método retornará um _stream_ de bytes (_byte stream_) codificado em utf-8. Se precisares de um _stream_ em outra codificação, veja projectos como o [iconv-lite](https:
```suggestion
> O _stream_ retornado por este método retornará um _stream_ de bytes (_byte stream_) codificado em utf-8. Se precisares de um _stream_ em outra codificação, vê projectos como o [iconv-lite](https://www.npmjs.com/package/iconv-lite), que fornecem _streams_ de transformação para transcodificação de texto.
```

2019-02-13 09:30 UTC, telmogoncalves commented on content/docs/reference-react-dom-server.md
> +Se tens planos de usar o React no cliente para tornar o _markup_ interactivo, não use este método. Em vez disso, use [`renderToNodeStream`](#rendertonodestream) no servidor e [`ReactDOM.hydrate()`](/
```suggestion
Se tens planos de usar o React no cliente para tornar o _markup_ interactivo, não uses este método. Em vez disso, usa [`renderToNodeStream`](#rendertonodestream) no servidor e [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) no cliente.
```

2019-02-13 09:30 UTC, telmogoncalves commented on content/docs/reference-react-dom-server.md
> +> O _stream_ retornado por este método retornará um _stream_ de bytes (_byte stream_) codificado em utf-8. Se precisares de um _stream_ em outra codificação, veja projectos como o [iconv-lite](https:
Esta parte não está repetida também?

2019-02-13 09:42 UTC, fjoshuajr commented on content/docs/reference-react-dom-server.md
> +Se invocares [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de eventos (_eve
Podemos fazer nó (_node_)?

2019-02-13 09:46 UTC, fjoshuajr commented on content/docs/reference-react-dom-server.md
> +> O _stream_ retornado por este método retornará um _stream_ de bytes (_byte stream_) codificado em utf-8. Se precisares de um _stream_ em outra codificação, veja projectos como o [iconv-lite](https:
É assim mesmo

2019-02-13 09:49 UTC, fjoshuajr commented on content/docs/reference-react-dom-server.md
> +> O _stream_ retornado por este método retornará um _stream_ de bytes (_byte stream_) codificado em utf-8. Se precisares de um _stream_ em outra codificação, veja projectos como o [iconv-lite](https:
```suggestion
> O _stream_ retornado por este método retornará um _stream_ de bytes (_byte stream_) codificado em utf-8. Se precisares de um _stream_ em outra codificação, vê projectos como o [iconv-lite](https://www.npmjs.com/package/iconv-lite), que fornecem _streams_ de transformação para transcodificação de texto.
```

2019-02-13 09:49 UTC, fjoshuajr commented on content/docs/reference-react-dom-server.md
> +Se tens planos de usar o React no cliente para tornar o _markup_ interactivo, não use este método. Em vez disso, use [`renderToString`](#rendertostring) no servidor e [`ReactDOM.hydrate()`](/docs/rea
```suggestion
Se tens planos de usar o React no cliente para tornar o _markup_ interactivo, não uses este método. Em vez disso, usa [`renderToString`](#rendertostring) no servidor e [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) no cliente.
```

2019-02-13 09:49 UTC, fjoshuajr commented on content/docs/reference-react-dom-server.md
> +Se invocares [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de eventos (_eve
É assim mesmo, cada método tem esta informacao

2019-02-13 14:09 UTC, 0xtelmo requested changes

2019-02-13 14:09 UTC, telmogoncalves commented on content/docs/reference-react-dom-server.md
> +Se invocares [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de eventos (_eve
Ainda não alteraste este. Acho que não deviamos traduzir a palavra `node`.

2019-02-13 20:52 UTC, fjoshuajr commented
@telmogoncalves já fiz as alterações.

2019-02-13 21:20 UTC, 0xtelmo submitted a review, later dismissed

2019-02-13 22:37 UTC, 0xtelmo submitted a review, later dismissed

2019-02-14 12:46 UTC, jbarradas requested changes

2019-02-14 12:46 UTC, jbarradas commented on content/docs/reference-react-dom-server.md
> +Renderiza um elemento React para o seu HTML inicial. O React retornará uma string HTML. Podes usar este método para gerar HTML no servidor e enviar o _markup_ no request inicial para ter carregamento
```suggestion
Renderiza um elemento React para o seu HTML inicial. O React retornará uma string HTML. Podes usar este método para gerar HTML no servidor e enviar o _markup_ no request inicial para ter carregamentos de páginas mais rápidos e para permitir que motores de pesquisa indexem as tuas páginas para fins de _SEO_.
```

2019-02-14 12:46 UTC, jbarradas commented on content/docs/reference-react-dom-server.md
> +Se invocares [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó (_node_) que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de even
```suggestion
Se invocares o método [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó (_node_) que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de eventos (_event handlers_), permitindo que tenhas uma experiência muito eficiente no primeiro carregamento.
```

2019-02-14 12:46 UTC, jbarradas commented on content/docs/reference-react-dom-server.md
> +Renderiza um elemento React para o teu HTML inicial. Retorna um [_Readable Stream_](https://nodejs.org/api/stream.html#stream_readable_streams) que gera uma string HTML. A saída HTML deste _stream_ é
```suggestion
Renderiza um elemento React para o teu HTML inicial. Retorna um [_Readable Stream_](https://nodejs.org/api/stream.html#stream_readable_streams) que gera uma string HTML. A saída HTML deste _stream_ é exactamente igual à que [`ReactDOMServer.renderToString`](#rendertostring) retornaria. Podes usar este método para gerar HTML no servidor e enviar o _markup_ no _request_ inicial para ter carregamentos de página mais rápidos e para permitir que motores de busca indexem as tuas páginas para fins de _SEO_.
```

2019-02-14 12:46 UTC, jbarradas commented on content/docs/reference-react-dom-server.md
> +Se invocares [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó (_node_) que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de even
```suggestion
Se invocares o método [`ReactDOM.hydrate()`](/docs/react-dom.html#hydrate) em um nó (_node_) que já tem o seu _markup_ processado pelo servidor, o React vai preservá-lo e apenas atribuir manipuladores de eventos (_event handlers_), permitindo que tenhas uma experiência muito eficiente no primeiro carregamento.
```

2019-02-14 22:25 UTC, fjoshuajr commented
@jbarradas já fiz as alterações.

2019-02-16 09:48 UTC, 0xtelmo approved these changes

2019-02-16 10:24 UTC, jbarradas approved these changes

2019-02-16 10:25 UTC, merged